services:
  _defaults:
    autowire: true
    autoconfigure: true

  artox_lab_clarc_message_bus.producer.event_message:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Producer\EventMessage\EventMessage

  ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Producer\EventMessage\EventMessageInterface: '@artox_lab_clarc_message_bus.producer.event_message'

  artox_lab_clarc_message_bus.consumer.created_event:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusCreatedEvent
    tags: [ 'artox_lab_clarc_message_bus.consumer.events' ]

  artox_lab_clarc_message_bus.consumer.updated_event:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusUpdatedEvent
    tags: [ 'artox_lab_clarc_message_bus.consumer.events' ]

  artox_lab_clarc_message_bus.consumer.deleted_event:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusDeletedEvent
    tags: [ 'artox_lab_clarc_message_bus.consumer.events' ]

  ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusCreatedEventInterface: '@artox_lab_clarc_message_bus.consumer.created_event'

  ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusUpdatedEventInterface: '@artox_lab_clarc_message_bus.consumer.updated_event'

  ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\Event\BusDeletedEventInterface: '@artox_lab_clarc_message_bus.consumer.deleted_event'

  artox_lab_clarc_message_bus.consumer.event_provider:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\EventProvider\BusEventProvider
    arguments: [ !tagged_iterator artox_lab_clarc_message_bus.consumer.events ]

  ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Consumer\EventProvider\BusEventProviderInterface: '@artox_lab_clarc_message_bus.consumer.event_provider'

  artox_lab_clarc_message_bus.middleware.add_redelivery_stamp_middleware:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Middleware\AddRedeliveryStampMiddleware

  artox_lab_clarc_message_bus.transport.bus_serializer:
    class: ArtoxLab\Bundle\ClarcMessageBusBundle\MessageBus\Interfaces\Transport\Serialization\BusSerializer
